services:
  db:
    image: postgres:17.2-alpine
    container_name: db_microservice
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: db_microservice
      POSTGRES_USER: db_microservice_user
      POSTGRES_PASSWORD: db_microservice_password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - net_microservice

volumes:
  db-data:


networks:
  net_microservice:
    driver: bridge
