services:
  db:
    image: postgres:17.2-alpine
    container_name: db_microservice
    ports:
      - "54322:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net_microservice

volumes:
  db-data:

networks:
  net_microservice:
    driver: bridge